CREATE TABLE "projectgpt_conversation_folder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projectgpt_conversation_folder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" varchar(255) NOT NULL,
	"folderId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projectgpt_folder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projectgpt_folder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(30) NOT NULL,
	"color" varchar(7) DEFAULT '#6366f1' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "projectgpt_conversation_folder" ADD CONSTRAINT "projectgpt_conversation_folder_folderId_projectgpt_folder_id_fk" FOREIGN KEY ("folderId") REFERENCES "public"."projectgpt_folder"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projectgpt_conversation_folder" ADD CONSTRAINT "projectgpt_conversation_folder_userId_projectgpt_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."projectgpt_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projectgpt_folder" ADD CONSTRAINT "projectgpt_folder_userId_projectgpt_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."projectgpt_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversation_folder_conversation_id_idx" ON "projectgpt_conversation_folder" USING btree ("conversationId");--> statement-breakpoint
CREATE INDEX "conversation_folder_folder_id_idx" ON "projectgpt_conversation_folder" USING btree ("folderId");--> statement-breakpoint
CREATE INDEX "conversation_folder_user_id_idx" ON "projectgpt_conversation_folder" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "conversation_folder_unique_idx" ON "projectgpt_conversation_folder" USING btree ("conversationId","folderId");--> statement-breakpoint
CREATE INDEX "folder_user_id_idx" ON "projectgpt_folder" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "folder_name_idx" ON "projectgpt_folder" USING btree ("name");